### ISSUE TITLE
Is this normal? (Generating bootstrap zip)

### ISSUE THREAD

**Issue by danielrosero** [termux/termux-packaging#2]
I'm running `generate-bootstraps.sh` with my parameters: -`-architectures aarch64 --prefix me.danielrosero.blastergram --repository https://danielroserobintray.bintray.com/blastergram/`

Managed to crate an APT repository in bintray, and the script finishes without problem.

But somehow I'm getting a zip without SYMLINKS.txt and only this content inside:

![bootstrap-content](https://user-images.githubusercontent.com/5695982/63099555-9695f680-bf75-11e9-8ab4-79ad8398ab02.png)

Is this normal?

Thanks for replying.

**Comment by danielrosero** [comment]
Just realized, the --prefix parameter goes as: /data/data/<your_ap_id>/files/usr

My bad.

**Comment by qianxin12568** [comment]
So,this project is just used to create a bootstrap.zip file?

**Comment by ghost** [comment]
>this project is just used to create a bootstrap.zip file?

\-\-\> https://github.com/termux/termux-packages/wiki/For-maintainers#generating-bootstrap-archives
