### ISSUE TITLE
Packaging 'libc++' failed

### ISSUE THREAD

**Issue by nokotan** [termux/termux-packaging#5]
When creating package 'libc++', I got following error:

```sh
AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'net.termux.libc++'
```

Seems that '+' is not valid character in an android package name.

**Comment by ghost** [comment]
Known issue. Package names can't have special symbols, so we have to rename libc++ to libcpp. This will not happen currently.

https://github.com/termux/termux-app/projects/1

**Comment by ghost** [comment]
Please note that Android 10 transition is in PRE-ALPHA state and is not being worked on.
